services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    build: .
    restart: always
    env_file:
      - .env.docker
    ports:
      - "8000:80"
    depends_on:
      - db
    entrypoint: ["/app/entrypoint.sh"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]

volumes:
  postgres_data:
    driver: local